### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by UndavalliJagadeesh** [UndavalliJagadeesh/auto-commit#1]
```
name: Daily Commit
on:
  schedule:
    - cron: "11 17 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Append number to file
        run: echo $(($(cat number.txt)+1)) > number.txt
      - name: Debug
        run: cat number.txt
      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "Jagadeesh Undavalli"
          git config user.email "20pa1a05h6@vishnu.edu.in"
          git add number.txt
          git commit -m "Added new number"
          git push https://github.com/UndavalliJagadeesh/git-daily-commit.git HEAD:main
```

Run git config user.name "Jagadeesh Undavalli"
[main 23866fe] Added new number
 1 file changed, 1 insertion(+), 1 deletion(-)
remote: Permission to UndavalliJagadeesh/git-daily-commit.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/UndavalliJagadeesh/git-daily-commit.git/': The requested URL returned error: 403
Error: Process completed with exit code [12](https://github.com/UndavalliJagadeesh/git-daily-commit/actions/runs/8160395342/job/22306886199#step:5:13)8.
